# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/H-Schott"

    [social.params]
        icon = "github"

[[social]]
    identifier = "bluesky"
    name       = "Bluesky"
    url        = "https://bsky.app/profile/hugoschott.bsky.social"

    [social.params]
        icon = "bluesky"

[[social]]
    identifier = "mail"
    name       = "mail"
    url        = "mailto:hugo.schott@liris.cnrs.fr"

    [social.params]
        icon = "gmail"

[[social]]
    identifier = "gscholar"
    name       = "gscholar"
    url        = "https://scholar.google.com/citations?user=QxzWUB8AAAAJ&hl=fr&oi=ao"

    [social.params]
        icon = "googlescholar"